# Generated by Django 3.1.5 on 2021-01-17 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20210117_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidkey',
            name='id',
        ),
        migrations.AddField(
            model_name='plaidkey',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plaidkey',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plaidkey',
            name='item_id',
            field=models.CharField(max_length=200),
        ),
    ]
